@startuml




class Utilisateur{
nom
prenom
mail
login
mot de passe
sexe
date de naissance
taille
poids
sommeil
poidsObjectif
}

class PlanEntrainement {
difficulté
durée
}

abstract class AbstractExercices {
titre
description
temps
}

enum sexe{
h
f
}

class aerobis{
distance
}

class anaerobis{ 
repetition
}

class Seance{
date
}

class Graph{

donnees
titre
description
}

Seance -- AbstractExercices
Seance -- Utilisateur

AbstractExercices <|--  aerobis
AbstractExercices <|--  anaerobis

PlanEntrainement o-- Utilisateur
PlanEntrainement o-- AbstractExercices

@enduml